using Cast.Cli.Models;
using Cast.Cli.Services;

namespace Cast.Cli.Tests;

public sealed class PlantUmlAngularDiagramRendererTests
{
    private static PlantUmlAngularDiagramRenderer CreateRenderer() => new();

    private static AngularService DashboardService() => new(
        "DashboardService",
        ConsumerKind.Service,
        IsFunctional: false,
        IsSingleton: true,
        ProvidedIn: "root",
        [
            new AngularDependency("HttpClient", DependencyKind.Service),
            new AngularDependency("API_BASE_URL", DependencyKind.Token),
        ]);

    private static AngularService AuthInterceptor() => new(
        "authInterceptor",
        ConsumerKind.Interceptor,
        IsFunctional: true,
        IsSingleton: false,
        ProvidedIn: null,
        [
            new AngularDependency("AuthStore", DependencyKind.Service),
            new AngularDependency("Router", DependencyKind.Service),
        ]);

    // Golden master: pins the full class (push) narrative — the user's reference scenario.
    [Fact]
    public void Render_ClassWithServiceAndToken_MatchesExactOutput()
    {
        string expected = string.Join("\n",
            "@startuml",
            "' Generated by cast ng",
            "title How Angular injects dependencies into DashboardService",
            "",
            "actor \"App\\n(a component or service\\nthat needs DashboardService)\" as App",
            "participant \"Angular Injector\\n(the built-in DI container)\" as DI",
            "participant \"DashboardService\\n(the consumer)\" as Consumer",
            "participant \"HttpClient\\n(injected service)\" as D1",
            "participant \"API_BASE_URL\\n(injected token)\" as D2",
            "",
            "App -> DI : Give me a DashboardService",
            "",
            "note over DI",
            "  Angular inspects DashboardService and sees it needs 2 dependencies:",
            "  - HttpClient (service)",
            "  - API_BASE_URL (token)",
            "end note",
            "",
            "DI -> D1 : resolve HttpClient",
            "activate D1",
            "D1 --> DI : the HttpClient instance",
            "deactivate D1",
            "",
            "note right of DI",
            "  API_BASE_URL is an InjectionToken, not a class.",
            "  Angular returns the value configured for it.",
            "end note",
            "DI -> D2 : look up API_BASE_URL",
            "activate D2",
            "D2 --> DI : the value for API_BASE_URL",
            "deactivate D2",
            "",
            "DI -> Consumer : create DashboardService",
            "activate Consumer",
            "note over Consumer",
            "  DashboardService never calls \"new ...()\" for its dependencies.",
            "  It declares them (via inject() or its constructor) and",
            "  Angular supplies them. That hand-off is the \"injection\".",
            "end note",
            "Consumer --> DI : the DashboardService instance",
            "deactivate Consumer",
            "note right of DI",
            "  @Injectable({ providedIn: 'root' }) means a singleton:",
            "  built once, then the same instance is shared with everyone.",
            "end note",
            "",
            "DI --> App : a ready-to-use DashboardService\\n(dependencies already wired inside)",
            "@enduml") + "\n";

        Assert.Equal(expected, CreateRenderer().Render(DashboardService()));
    }

    // Golden master: pins the full functional (pull) narrative.
    [Fact]
    public void Render_FunctionalInterceptor_MatchesExactOutput()
    {
        string expected = string.Join("\n",
            "@startuml",
            "' Generated by cast ng",
            "title How Angular wires dependencies into authInterceptor (HTTP interceptor)",
            "",
            "participant \"Angular HttpClient\\n(runs the interceptor per request)\" as App",
            "participant \"Angular Injector\\n(the built-in DI container)\" as DI",
            "participant \"authInterceptor\\n(the consumer)\" as Consumer",
            "participant \"AuthStore\\n(injected service)\" as D1",
            "participant \"Router\\n(injected service)\" as D2",
            "",
            "App -> DI : run authInterceptor for an HTTP request",
            "activate Consumer",
            "",
            "note over Consumer",
            "  authInterceptor runs inside an injection context, so it",
            "  can call inject(...) to pull each dependency it needs.",
            "end note",
            "",
            "Consumer -> DI : inject(AuthStore)",
            "DI -> D1 : resolve AuthStore",
            "activate D1",
            "D1 --> DI : the AuthStore instance",
            "deactivate D1",
            "DI --> Consumer : the AuthStore instance",
            "",
            "Consumer -> DI : inject(Router)",
            "DI -> D2 : resolve Router",
            "activate D2",
            "D2 --> DI : the Router instance",
            "deactivate D2",
            "DI --> Consumer : the Router instance",
            "",
            "note over Consumer",
            "  authInterceptor never wrote \"new AuthStore()\" — it asked the",
            "  injector for what it needed. That hand-off is the \"injection\".",
            "end note",
            "Consumer --> App : forwards the request",
            "deactivate Consumer",
            "@enduml") + "\n";

        Assert.Equal(expected, CreateRenderer().Render(AuthInterceptor()));
    }

    [Fact]
    public void Render_AlwaysWrapsInStartAndEnd_WithTrailingNewline_NoCarriageReturn()
    {
        string output = CreateRenderer().Render(DashboardService());

        Assert.StartsWith("@startuml\n", output);
        Assert.EndsWith("@enduml\n", output);
        Assert.DoesNotContain("\r", output);
    }

    [Fact]
    public void Render_CustomTitle_OverridesGeneratedTitle()
    {
        string output = CreateRenderer().Render(DashboardService(), "My DI Story");

        Assert.Contains("title My DI Story\n", output);
        Assert.DoesNotContain("How Angular injects", output);
    }

    [Fact]
    public void Render_NonSingleton_OmitsSingletonNote()
    {
        var service = DashboardService() with { IsSingleton = false, ProvidedIn = null };

        string output = CreateRenderer().Render(service);

        Assert.DoesNotContain("means a singleton", output);
    }

    [Fact]
    public void Render_ZeroDependencies_NoteSaysNoDependencies()
    {
        var service = new AngularService("AuthStore", ConsumerKind.Store, false, true, "root", []);

        string output = CreateRenderer().Render(service);

        Assert.Contains("finds\n  no injected dependencies.", output);
        Assert.Contains("has no dependencies to inject", output);
        Assert.DoesNotContain(" as D1", output); // no dependency lifelines declared
    }

    [Fact]
    public void Render_MultipleTokens_ExplainsInjectionTokenOnlyOnce()
    {
        var service = new AngularService(
            "TwoTokenService", ConsumerKind.Service, false, true, "root",
            [
                new AngularDependency("FIRST_TOKEN", DependencyKind.Token),
                new AngularDependency("SECOND_TOKEN", DependencyKind.Token),
            ]);

        string output = CreateRenderer().Render(service);

        int occurrences = output.Split("is an InjectionToken").Length - 1;
        Assert.Equal(1, occurrences);
    }

    [Fact]
    public void Render_OptionalDependency_LabelsItOptional()
    {
        var service = new AngularService(
            "OptService", ConsumerKind.Service, false, false, null,
            [new AngularDependency("Telemetry", DependencyKind.Service, Optional: true)]);

        string output = CreateRenderer().Render(service);

        Assert.Contains("(injected service, optional)", output);
        Assert.Contains("- Telemetry (service, optional)", output);
    }

    [Fact]
    public void Render_FunctionalGuard_UsesRouterCallerAndDecision()
    {
        var service = new AngularService(
            "authGuard", ConsumerKind.Guard, IsFunctional: true, false, null,
            [new AngularDependency("AuthStore", DependencyKind.Service)]);

        string output = CreateRenderer().Render(service);

        Assert.Contains("title How Angular wires dependencies into authGuard (route guard)", output);
        Assert.Contains("participant \"Angular Router\\n(checks the guard on navigation)\" as App", output);
        Assert.Contains("App -> DI : run authGuard for a navigation", output);
        Assert.Contains("Consumer --> App : returns its decision", output);
    }

    [Fact]
    public void Render_FunctionalResolver_UsesRouterCallerAndResolvedData()
    {
        var service = new AngularService(
            "userResolver", ConsumerKind.Resolver, IsFunctional: true, false, null,
            [new AngularDependency("UserService", DependencyKind.Service)]);

        string output = CreateRenderer().Render(service);

        Assert.Contains("(route resolver)", output);
        Assert.Contains("participant \"Angular Router\\n(resolves data before navigation)\" as App", output);
        Assert.Contains("App -> DI : run userResolver before navigating", output);
        Assert.Contains("Consumer --> App : returns the resolved data", output);
    }

    [Fact]
    public void Render_FunctionalNoDependencies_NoteSaysInjectsNothing()
    {
        var service = new AngularService("emptyGuard", ConsumerKind.Guard, IsFunctional: true, false, null, []);

        string output = CreateRenderer().Render(service);

        Assert.Contains("but injects no dependencies.", output);
        Assert.DoesNotContain("inject(", output);
        Assert.DoesNotContain("never wrote", output);
        Assert.Contains("Angular Router", output);
    }

    [Fact]
    public void Render_ServiceWithVowelInitialName_UsesAn()
    {
        var service = new AngularService("OrderService", ConsumerKind.Service, false, false, null, []);

        Assert.Contains("App -> DI : Give me an OrderService", CreateRenderer().Render(service));
    }

    [Theory]
    [InlineData(ConsumerKind.Component, "building the component tree")]
    [InlineData(ConsumerKind.Directive, "building a view")]
    [InlineData(ConsumerKind.Pipe, "rendering a template")]
    public void Render_ComponentDirectivePipe_UsesAngularRuntimeCaller(ConsumerKind kind, string callerHint)
    {
        var service = new AngularService("Widget", kind, false, false, null, []);

        string output = CreateRenderer().Render(service);

        Assert.Contains($"participant \"Angular runtime\\n({callerHint})\" as App", output);
        Assert.Contains("App -> DI : create a Widget", output);
    }
}
