using System.Collections.Generic;
using Cast.Cli.Models;

namespace Cast.Cli.Services;

/// <summary>
/// Renders the Angular dependency-injection story as PlantUML. A class consumer is shown the way
/// Angular builds it — the injector resolves each dependency, then constructs the class with them
/// (a "push"). A functional provider is shown the way it runs — the function pulls each dependency
/// through <c>inject()</c> while executing (a "pull"). In both cases the diagram names every
/// injected service and token so the wiring is explicit.
/// Every diagram runs the teoz engine (<c>!pragma teoz true</c>) with a default font size of 10,
/// colors every lifeline <see cref="DiagramStyle.ParticipantColor"/>, and wraps the participant
/// lifelines in a double nested box (outer/inner colors from <see cref="DiagramStyle"/>); an
/// actor caller stays outside the boxes.
/// Output uses <c>\n</c> line endings for deterministic, platform-independent results.
/// </summary>
public sealed class PlantUmlAngularDiagramRenderer : IAngularDiagramRenderer
{
    private const string Newline = "\n";

    /// <inheritdoc />
    public string Render(AngularService service, string? title = null, DiagramStyle? style = null)
    {
        style ??= DiagramStyle.Default;

        var lines = new List<string>
        {
            "@startuml",
            "' Generated by cast ng",
            "!pragma teoz true",
            "skinparam defaultFontSize 10",
            $"title {Title(service, title)}",
            string.Empty,
        };

        (string callerDecl, string ask) = Caller(service);
        callerDecl = $"{callerDecl} {DiagramStyle.ParticipantColor}";

        // Participant lifelines live inside the double box; an actor caller stays outside it.
        var boxed = new List<string>();
        if (callerDecl.StartsWith("actor ", StringComparison.Ordinal))
        {
            lines.Add(callerDecl);
        }
        else
        {
            boxed.Add(callerDecl);
        }

        boxed.Add($"participant \"Angular Injector\\n(the built-in DI container)\" as DI {DiagramStyle.ParticipantColor}");
        boxed.Add($"participant \"{service.Name}\\n(the consumer)\" as Consumer {DiagramStyle.ParticipantColor}");
        DeclareDependencies(boxed, service.Dependencies);

        lines.Add($"box {style.OuterBoxColor}");
        lines.Add($"  box {style.InnerBoxColor}");
        foreach (string declaration in boxed)
        {
            lines.Add($"    {declaration}");
        }

        lines.Add("  end box");
        lines.Add("end box");

        lines.Add(string.Empty);

        if (service.IsFunctional)
        {
            RenderFunctional(lines, service, ask);
        }
        else
        {
            RenderClass(lines, service, ask);
        }

        lines.Add("@enduml");
        return string.Join(Newline, lines) + Newline;
    }

    // ----- class (push) -------------------------------------------------------------------

    private static void RenderClass(List<string> lines, AngularService service, string ask)
    {
        IReadOnlyList<AngularDependency> deps = service.Dependencies;

        lines.Add($"App -> DI : {ask}");
        lines.Add(string.Empty);

        AddInspectNote(lines, service);
        lines.Add(string.Empty);

        bool tokenExplained = false;
        foreach ((AngularDependency dep, int index) in Indexed(deps))
        {
            EmitResolution(lines, dep, index, ref tokenExplained);
            lines.Add(string.Empty);
        }

        lines.Add($"DI -> Consumer : create {service.Name}");
        lines.Add("activate Consumer");
        AddConstructionNote(lines, service);
        lines.Add($"Consumer --> DI : the {service.Name} instance");
        lines.Add("deactivate Consumer");

        AddSingletonNote(lines, service);

        lines.Add(string.Empty);
        lines.Add($"DI --> App : a ready-to-use {service.Name}\\n(dependencies already wired inside)");
    }

    // ----- functional (pull) --------------------------------------------------------------

    private static void RenderFunctional(List<string> lines, AngularService service, string ask)
    {
        IReadOnlyList<AngularDependency> deps = service.Dependencies;

        lines.Add($"App -> DI : {ask}");
        lines.Add("activate Consumer");
        lines.Add(string.Empty);

        if (deps.Count == 0)
        {
            Note(lines, "over Consumer",
                $"{service.Name} runs inside an injection context",
                "but injects no dependencies.");
        }
        else
        {
            Note(lines, "over Consumer",
                $"{service.Name} runs inside an injection context, so it",
                "can call inject(...) to pull each dependency it needs.");
        }

        lines.Add(string.Empty);

        bool tokenExplained = false;
        foreach ((AngularDependency dep, int index) in Indexed(deps))
        {
            lines.Add($"Consumer -> DI : inject({dep.Name})");
            EmitResolution(lines, dep, index, ref tokenExplained);
            lines.Add($"DI --> Consumer : {Returned(dep)}");
            lines.Add(string.Empty);
        }

        if (deps.Count > 0)
        {
            Note(lines, "over Consumer",
                $"{service.Name} never wrote \"new {deps[0].Name}()\" — it asked the",
                "injector for what it needed. That hand-off is the \"injection\".");
        }

        lines.Add($"Consumer --> App : {Done(service.Kind)}");
        lines.Add("deactivate Consumer");
    }

    // ----- shared bits --------------------------------------------------------------------

    /// <summary>Emits the injector resolving one dependency from its own lifeline.</summary>
    private static void EmitResolution(List<string> lines, AngularDependency dep, int index, ref bool tokenExplained)
    {
        string alias = $"D{index + 1}";

        if (dep.Kind == DependencyKind.Token)
        {
            if (!tokenExplained)
            {
                Note(lines, "right of DI",
                    $"{dep.Name} is an InjectionToken, not a class.",
                    "Angular returns the value configured for it.");
                tokenExplained = true;
            }

            lines.Add($"DI -> {alias} : look up {dep.Name}");
            lines.Add($"activate {alias}");
            lines.Add($"{alias} --> DI : the value for {dep.Name}");
            lines.Add($"deactivate {alias}");
        }
        else
        {
            lines.Add($"DI -> {alias} : resolve {dep.Name}");
            lines.Add($"activate {alias}");
            lines.Add($"{alias} --> DI : the {dep.Name} instance");
            lines.Add($"deactivate {alias}");
        }
    }

    private static void DeclareDependencies(List<string> lines, IReadOnlyList<AngularDependency> deps)
    {
        foreach ((AngularDependency dep, int index) in Indexed(deps))
        {
            string role = dep.Kind == DependencyKind.Token ? "injected token" : "injected service";
            if (dep.Optional)
            {
                role += ", optional";
            }

            lines.Add($"participant \"{dep.Name}\\n({role})\" as D{index + 1} {DiagramStyle.ParticipantColor}");
        }
    }

    private static void AddInspectNote(List<string> lines, AngularService service)
    {
        IReadOnlyList<AngularDependency> deps = service.Dependencies;
        if (deps.Count == 0)
        {
            Note(lines, "over DI", $"Angular inspects {service.Name} and finds", "no injected dependencies.");
            return;
        }

        string count = deps.Count == 1 ? "1 dependency" : $"{deps.Count} dependencies";
        var content = new List<string> { $"Angular inspects {service.Name} and sees it needs {count}:" };
        foreach (AngularDependency dep in deps)
        {
            string kind = dep.Kind == DependencyKind.Token ? "token" : "service";
            string suffix = dep.Optional ? ", optional" : string.Empty;
            content.Add($"- {dep.Name} ({kind}{suffix})");
        }

        Note(lines, "over DI", content);
    }

    private static void AddConstructionNote(List<string> lines, AngularService service)
    {
        if (service.Dependencies.Count == 0)
        {
            Note(lines, "over Consumer",
                $"{service.Name} has no dependencies to inject;",
                "Angular just constructs it.");
            return;
        }

        Note(lines, "over Consumer",
            $"{service.Name} never calls \"new ...()\" for its dependencies.",
            "It declares them (via inject() or its constructor) and",
            "Angular supplies them. That hand-off is the \"injection\".");
    }

    private static void AddSingletonNote(List<string> lines, AngularService service)
    {
        if (!service.IsSingleton)
        {
            return;
        }

        Note(lines, "right of DI",
            $"@Injectable({{ providedIn: '{service.ProvidedIn}' }}) means a singleton:",
            "built once, then the same instance is shared with everyone.");
    }

    // ----- wording ------------------------------------------------------------------------

    private static string Title(AngularService service, string? title)
    {
        if (!string.IsNullOrWhiteSpace(title))
        {
            return title.Trim();
        }

        return service.IsFunctional
            ? $"How Angular wires dependencies into {service.Name} ({KindLabel(service.Kind)})"
            : $"How Angular injects dependencies into {service.Name}";
    }

    /// <summary>The caller lifeline declaration plus the message that kicks off the interaction.</summary>
    private static (string CallerDeclaration, string Ask) Caller(AngularService service)
    {
        string name = service.Name;

        if (service.IsFunctional)
        {
            return service.Kind switch
            {
                ConsumerKind.Interceptor => (
                    "participant \"Angular HttpClient\\n(runs the interceptor per request)\" as App",
                    $"run {name} for an HTTP request"),
                ConsumerKind.Guard => (
                    "participant \"Angular Router\\n(checks the guard on navigation)\" as App",
                    $"run {name} for a navigation"),
                ConsumerKind.Resolver => (
                    "participant \"Angular Router\\n(resolves data before navigation)\" as App",
                    $"run {name} before navigating"),
                _ => (
                    "participant \"Angular\\n(in an injection context)\" as App",
                    $"run {name}"),
            };
        }

        return service.Kind switch
        {
            ConsumerKind.Component => (
                "participant \"Angular runtime\\n(building the component tree)\" as App",
                $"create a {name}"),
            ConsumerKind.Directive => (
                "participant \"Angular runtime\\n(building a view)\" as App",
                $"create a {name}"),
            ConsumerKind.Pipe => (
                "participant \"Angular runtime\\n(rendering a template)\" as App",
                $"create a {name}"),
            _ => (
                $"actor \"App\\n(a component or service\\nthat needs {name})\" as App",
                $"Give me {Article(name)} {name}"),
        };
    }

    private static string KindLabel(ConsumerKind kind) => kind switch
    {
        ConsumerKind.Interceptor => "HTTP interceptor",
        ConsumerKind.Guard => "route guard",
        ConsumerKind.Resolver => "route resolver",
        _ => "function",
    };

    private static string Done(ConsumerKind kind) => kind switch
    {
        ConsumerKind.Interceptor => "forwards the request",
        ConsumerKind.Guard => "returns its decision",
        ConsumerKind.Resolver => "returns the resolved data",
        _ => "returns its result",
    };

    private static string Returned(AngularDependency dep) =>
        dep.Kind == DependencyKind.Token ? $"the value for {dep.Name}" : $"the {dep.Name} instance";

    private static string Article(string name) =>
        name.Length > 0 && "AEIOUaeiou".IndexOf(name[0]) >= 0 ? "an" : "a";

    // ----- note emission ------------------------------------------------------------------

    private static void Note(List<string> lines, string anchor, params string[] content) =>
        Note(lines, anchor, (IReadOnlyList<string>)content);

    private static void Note(List<string> lines, string anchor, IReadOnlyList<string> content)
    {
        lines.Add($"note {anchor}");
        foreach (string line in content)
        {
            lines.Add($"  {line}");
        }

        lines.Add("end note");
    }

    private static IEnumerable<(T Item, int Index)> Indexed<T>(IReadOnlyList<T> items)
    {
        for (int i = 0; i < items.Count; i++)
        {
            yield return (items[i], i);
        }
    }
}
