using System.Collections.Generic;
using Cast.Cli.Models;

namespace Cast.Cli.Services;

/// <summary>
/// Renders a <see cref="CallGraph"/> as PlantUML: an external <c>Caller</c> actor invokes each of the
/// subject's methods in turn, and under every method the calls it makes are drawn — self calls loop
/// back to the subject, collaborator calls go to their own lifelines, and a <c>new T(...)</c> shows a
/// "«create»" arrow. Each method is separated by a <c>== signature ==</c> divider.
/// Every diagram runs the teoz engine (<c>!pragma teoz true</c>) with a default font size of 10,
/// colors every lifeline <see cref="DiagramStyle.ParticipantColor"/>, and wraps the non-actor
/// lifelines in a double nested box (outer/inner colors from <see cref="DiagramStyle"/>); the
/// <c>Caller</c> actor stays outside the boxes.
/// Output uses <c>\n</c> line endings for deterministic, platform-independent results.
/// </summary>
public sealed class PlantUmlCallGraphRenderer : ICallGraphRenderer
{
    private const string Newline = "\n";
    private const string SubjectAlias = "C0";

    /// <inheritdoc />
    public string Render(CallGraph graph, string? title = null, DiagramStyle? style = null)
    {
        style ??= DiagramStyle.Default;

        var lines = new List<string>
        {
            "@startuml",
            "' Generated by cast calls",
            "!pragma teoz true",
            "skinparam defaultFontSize 10",
            $"title {Title(graph, title)}",
            string.Empty,
        };

        // Assign a stable alias to every distinct collaborator, in first-appearance order. A call
        // whose receiver is the subject itself folds back onto the subject lifeline.
        var aliasByKey = new Dictionary<string, string>(StringComparer.Ordinal);
        var collaborators = new List<(string Alias, string Label)>();
        foreach (CallGraphMethod method in graph.Methods)
        {
            foreach (MethodCall call in method.Calls)
            {
                if (call.Kind == CallKind.Self || call.ReceiverKey == graph.SubjectName)
                {
                    continue;
                }

                if (!aliasByKey.ContainsKey(call.ReceiverKey))
                {
                    string alias = $"C{collaborators.Count + 1}";
                    aliasByKey[call.ReceiverKey] = alias;
                    collaborators.Add((alias, call.ReceiverLabel));
                }
            }
        }

        lines.Add($"actor \"Caller\\n(external code)\" as Caller {DiagramStyle.ParticipantColor}");
        lines.Add($"box {style.OuterBoxColor}");
        lines.Add($"  box {style.InnerBoxColor}");
        lines.Add($"    participant \"{graph.SubjectName}\\n({SubjectRole(graph.Kind)})\" as {SubjectAlias} {DiagramStyle.ParticipantColor}");
        foreach ((string alias, string label) in collaborators)
        {
            lines.Add($"    participant \"{label}\" as {alias} {DiagramStyle.ParticipantColor}");
        }

        lines.Add("  end box");
        lines.Add("end box");

        foreach (CallGraphMethod method in graph.Methods)
        {
            lines.Add(string.Empty);
            lines.Add($"== {method.Signature} ==");
            lines.Add($"Caller -> {SubjectAlias} : {method.Signature}");
            lines.Add($"activate {SubjectAlias}");
            RenderCalls(lines, method, aliasByKey);
            lines.Add($"deactivate {SubjectAlias}");
        }

        lines.Add("@enduml");
        return string.Join(Newline, lines) + Newline;
    }

    private static void RenderCalls(List<string> lines, CallGraphMethod method, IReadOnlyDictionary<string, string> aliasByKey)
    {
        if (method.Calls.Count == 0)
        {
            lines.Add($"note over {SubjectAlias}");
            lines.Add("  (no outbound calls)");
            lines.Add("end note");
            return;
        }

        foreach (MethodCall call in method.Calls)
        {
            switch (call.Kind)
            {
                case CallKind.Self:
                    lines.Add($"{SubjectAlias} -> {SubjectAlias} : {call.Method}()");
                    break;
                case CallKind.Construction:
                    lines.Add($"{SubjectAlias} -> {AliasFor(call, aliasByKey)} : «create»");
                    break;
                default:
                    lines.Add($"{SubjectAlias} -> {AliasFor(call, aliasByKey)} : {call.Method}()");
                    break;
            }
        }
    }

    /// <summary>Resolves the lifeline alias for a call, folding self-named receivers back onto the subject.</summary>
    private static string AliasFor(MethodCall call, IReadOnlyDictionary<string, string> aliasByKey) =>
        aliasByKey.TryGetValue(call.ReceiverKey, out string? alias) ? alias : SubjectAlias;

    private static string Title(CallGraph graph, string? title)
    {
        if (!string.IsNullOrWhiteSpace(title))
        {
            return title.Trim();
        }

        return graph.Kind == CallGraphSubjectKind.Module
            ? $"Call graph of {graph.SubjectName} (module functions)"
            : $"Call graph of {graph.SubjectName}";
    }

    private static string SubjectRole(CallGraphSubjectKind kind) =>
        kind == CallGraphSubjectKind.Module ? "this module" : "the class under inspection";
}
